#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/oneplus/infiniti-camera

PRODUCT_COPY_FILES += \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/fb_model/000.png:$(TARGET_COPY_OUT_ODM)/etc/camera/fb_model/000.png \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/fb_model/000_pre.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/fb_model/000_pre.bin \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/fb_model/000_pre.png:$(TARGET_COPY_OUT_ODM)/etc/camera/fb_model/000_pre.png \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/fb_model/001.png:$(TARGET_COPY_OUT_ODM)/etc/camera/fb_model/001.png \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/fb_model/001_pre.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/fb_model/001_pre.bin \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/fb_model/001_pre.png:$(TARGET_COPY_OUT_ODM)/etc/camera/fb_model/001_pre.png \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/fb_model/002.png:$(TARGET_COPY_OUT_ODM)/etc/camera/fb_model/002.png \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/fb_model/002_pre.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/fb_model/002_pre.bin \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/fb_model/003.png:$(TARGET_COPY_OUT_ODM)/etc/camera/fb_model/003.png \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/fb_model/003_pre.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/fb_model/003_pre.bin \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/fb_model/003_pre.png:$(TARGET_COPY_OUT_ODM)/etc/camera/fb_model/003_pre.png \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/fb_model/010.png:$(TARGET_COPY_OUT_ODM)/etc/camera/fb_model/010.png \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/fb_model/010_pre.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/fb_model/010_pre.bin \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/fb_model/010_pre.png:$(TARGET_COPY_OUT_ODM)/etc/camera/fb_model/010_pre.png \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/fb_model/011.png:$(TARGET_COPY_OUT_ODM)/etc/camera/fb_model/011.png \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/fb_model/011_pre.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/fb_model/011_pre.bin \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/fb_model/011_pre.png:$(TARGET_COPY_OUT_ODM)/etc/camera/fb_model/011_pre.png \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/fb_model/012.png:$(TARGET_COPY_OUT_ODM)/etc/camera/fb_model/012.png \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/fb_model/012_pre.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/fb_model/012_pre.bin \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/fb_model/013.png:$(TARGET_COPY_OUT_ODM)/etc/camera/fb_model/013.png \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/fb_model/100.png:$(TARGET_COPY_OUT_ODM)/etc/camera/fb_model/100.png \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/fb_model/100_pre.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/fb_model/100_pre.bin \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/fb_model/101.png:$(TARGET_COPY_OUT_ODM)/etc/camera/fb_model/101.png \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/fb_model/101_pre.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/fb_model/101_pre.bin \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/fb_model/102.png:$(TARGET_COPY_OUT_ODM)/etc/camera/fb_model/102.png \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/fb_model/102_pre.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/fb_model/102_pre.bin \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/fb_model/103.png:$(TARGET_COPY_OUT_ODM)/etc/camera/fb_model/103.png \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/fb_model/103_pre.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/fb_model/103_pre.bin \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/fb_model/110.png:$(TARGET_COPY_OUT_ODM)/etc/camera/fb_model/110.png \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/fb_model/110_pre.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/fb_model/110_pre.bin \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/fb_model/111.png:$(TARGET_COPY_OUT_ODM)/etc/camera/fb_model/111.png \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/fb_model/111_pre.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/fb_model/111_pre.bin \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/fb_model/112.png:$(TARGET_COPY_OUT_ODM)/etc/camera/fb_model/112.png \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/fb_model/112_pre.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/fb_model/112_pre.bin \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/fb_model/113.png:$(TARGET_COPY_OUT_ODM)/etc/camera/fb_model/113.png \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/fb_model/200.png:$(TARGET_COPY_OUT_ODM)/etc/camera/fb_model/200.png \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/fb_model/200_pre.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/fb_model/200_pre.bin \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/fb_model/201.png:$(TARGET_COPY_OUT_ODM)/etc/camera/fb_model/201.png \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/fb_model/201_pre.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/fb_model/201_pre.bin \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/fb_model/202.png:$(TARGET_COPY_OUT_ODM)/etc/camera/fb_model/202.png \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/fb_model/202_pre.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/fb_model/202_pre.bin \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/fb_model/203.png:$(TARGET_COPY_OUT_ODM)/etc/camera/fb_model/203.png \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/fb_model/203_pre.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/fb_model/203_pre.bin \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/fb_model/210.png:$(TARGET_COPY_OUT_ODM)/etc/camera/fb_model/210.png \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/fb_model/210_pre.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/fb_model/210_pre.bin \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/fb_model/211.png:$(TARGET_COPY_OUT_ODM)/etc/camera/fb_model/211.png \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/fb_model/211_pre.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/fb_model/211_pre.bin \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/fb_model/212.png:$(TARGET_COPY_OUT_ODM)/etc/camera/fb_model/212.png \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/fb_model/212_pre.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/fb_model/212_pre.bin \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/fb_model/213.png:$(TARGET_COPY_OUT_ODM)/etc/camera/fb_model/213.png \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/fb_model/AIdeblemishSnapMask.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/fb_model/AIdeblemishSnapMask.bin \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/fb_model/AIdeblemishSnapMask.png:$(TARGET_COPY_OUT_ODM)/etc/camera/fb_model/AIdeblemishSnapMask.png \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/fb_model/AIdeblemishSnapMask2.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/fb_model/AIdeblemishSnapMask2.bin \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/fb_model/SkinLUT_00.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/fb_model/SkinLUT_00.bin \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/fb_model/SkinLUT_01.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/fb_model/SkinLUT_01.bin \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/fb_model/SkinLUT_02.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/fb_model/SkinLUT_02.bin \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/fb_model/SkinLUT_03.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/fb_model/SkinLUT_03.bin \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/fb_model/SkinLUT_10.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/fb_model/SkinLUT_10.bin \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/fb_model/SkinLUT_11.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/fb_model/SkinLUT_11.bin \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/fb_model/SkinLUT_12.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/fb_model/SkinLUT_12.bin \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/fb_model/SkinLUT_13.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/fb_model/SkinLUT_13.bin \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/fb_model/SkinLUT_BW.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/fb_model/SkinLUT_BW.bin \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/fb_model/SkinLUT_Red.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/fb_model/SkinLUT_Red.bin \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/fb_model/beauty_body.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/fb_model/beauty_body.bin \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/fb_model/brightLut.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/fb_model/brightLut.bin \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/fb_model/brightLut.png:$(TARGET_COPY_OUT_ODM)/etc/camera/fb_model/brightLut.png \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/fb_model/eyeBright.png:$(TARGET_COPY_OUT_ODM)/etc/camera/fb_model/eyeBright.png \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/fb_model/eye_retouch_chinese.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/fb_model/eye_retouch_chinese.bin \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/fb_model/eyesMask.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/fb_model/eyesMask.bin \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/fb_model/eyesMask.png:$(TARGET_COPY_OUT_ODM)/etc/camera/fb_model/eyesMask.png \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/fb_model/eyesMaskNew.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/fb_model/eyesMaskNew.bin \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/fb_model/eyesMaskNew.png:$(TARGET_COPY_OUT_ODM)/etc/camera/fb_model/eyesMaskNew.png \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/fb_model/face_eyeRed_chinese.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/fb_model/face_eyeRed_chinese.bin \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/fb_model/face_faceshadow_chinese.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/fb_model/face_faceshadow_chinese.bin \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/fb_model/face_facewarp_chinese.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/fb_model/face_facewarp_chinese.bin \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/fb_model/face_retouch_chinese.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/fb_model/face_retouch_chinese.bin \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/fb_model/face_retouch_pre_chinese.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/fb_model/face_retouch_pre_chinese.bin \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/fb_model/face_retouch_pre_chinese_wechat.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/fb_model/face_retouch_pre_chinese_wechat.bin \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/fb_model/faceshine_base.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/fb_model/faceshine_base.bin \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/fb_model/mouthmask.png:$(TARGET_COPY_OUT_ODM)/etc/camera/fb_model/mouthmask.png \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/fb_model/preSkinmask137.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/fb_model/preSkinmask137.bin \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/fb_model/preSkinmask137.png:$(TARGET_COPY_OUT_ODM)/etc/camera/fb_model/preSkinmask137.png \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/fb_model/preSkinmask296.png:$(TARGET_COPY_OUT_ODM)/etc/camera/fb_model/preSkinmask296.png \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/fb_model/redToneLut.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/fb_model/redToneLut.bin \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/fb_model/redToneLut.png:$(TARGET_COPY_OUT_ODM)/etc/camera/fb_model/redToneLut.png \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/fb_model/skinLUT_white_Bright.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/fb_model/skinLUT_white_Bright.bin \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/fb_model/skinLUTs00.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/fb_model/skinLUTs00.bin \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/fb_model/skinLUTs01.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/fb_model/skinLUTs01.bin \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/fb_model/skinLUTs02.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/fb_model/skinLUTs02.bin \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/fb_model/skinLUTs03.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/fb_model/skinLUTs03.bin \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/fb_model/skinLUTs04.png:$(TARGET_COPY_OUT_ODM)/etc/camera/fb_model/skinLUTs04.png \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/fb_model/skinLUTs05.png:$(TARGET_COPY_OUT_ODM)/etc/camera/fb_model/skinLUTs05.png \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/fb_model/skinLUTs06.png:$(TARGET_COPY_OUT_ODM)/etc/camera/fb_model/skinLUTs06.png \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/fb_model/skinLUTs10.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/fb_model/skinLUTs10.bin \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/fb_model/skinLUTs11.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/fb_model/skinLUTs11.bin \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/fb_model/skinLUTs12.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/fb_model/skinLUTs12.bin \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/fb_model/skinLUTs13.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/fb_model/skinLUTs13.bin \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/fb_model/skinLUTs_yuv16_00.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/fb_model/skinLUTs_yuv16_00.bin \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/fb_model/skinLUTs_yuv16_01.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/fb_model/skinLUTs_yuv16_01.bin \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/fb_model/skinLUTs_yuv16_02.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/fb_model/skinLUTs_yuv16_02.bin \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/fb_model/skinLUTs_yuv16_03.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/fb_model/skinLUTs_yuv16_03.bin \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/fb_model/skinLUTs_yuv16_10.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/fb_model/skinLUTs_yuv16_10.bin \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/fb_model/skinLUTs_yuv16_11.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/fb_model/skinLUTs_yuv16_11.bin \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/fb_model/skinLUTs_yuv16_12.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/fb_model/skinLUTs_yuv16_12.bin \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/fb_model/skinLUTs_yuv16_13.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/fb_model/skinLUTs_yuv16_13.bin \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/fb_model/skinmask.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/fb_model/skinmask.bin \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/fb_model/skinmask.png:$(TARGET_COPY_OUT_ODM)/etc/camera/fb_model/skinmask.png \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/fb_model/skinmask_new.png:$(TARGET_COPY_OUT_ODM)/etc/camera/fb_model/skinmask_new.png \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/fb_model/snapEyeBright.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/fb_model/snapEyeBright.bin \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/fb_model/snapEyeMask.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/fb_model/snapEyeMask.bin \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/fb_model/snapEyeMask.png:$(TARGET_COPY_OUT_ODM)/etc/camera/fb_model/snapEyeMask.png \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/fb_model/snapFemale000.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/fb_model/snapFemale000.bin \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/fb_model/snapFemale001.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/fb_model/snapFemale001.bin \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/fb_model/snapFemale002.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/fb_model/snapFemale002.bin \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/fb_model/snapFemale003.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/fb_model/snapFemale003.bin \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/fb_model/snapMale010.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/fb_model/snapMale010.bin \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/fb_model/snapMale011.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/fb_model/snapMale011.bin \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/fb_model/snapMale012.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/fb_model/snapMale012.bin \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/fb_model/snapMouthMask.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/fb_model/snapMouthMask.bin \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/fb_model/snapSkinmask.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/fb_model/snapSkinmask.bin \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/fb_model/unify_skin_base.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/fb_model/unify_skin_base.bin \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/fb_model/whiteToneLut.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/fb_model/whiteToneLut.bin \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/fb_model/whiteToneLut.png:$(TARGET_COPY_OUT_ODM)/etc/camera/fb_model/whiteToneLut.png \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/pfb_bin/PreCalVarBinary.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/pfb_bin/PreCalVarBinary.bin \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/pfb_bin/PreHighPassBinary.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/pfb_bin/PreHighPassBinary.bin \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/pfb_bin/PreHighPassPreBinary.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/pfb_bin/PreHighPassPreBinary.bin \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/pfb_bin/PreHoriFilterBinary.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/pfb_bin/PreHoriFilterBinary.bin \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/pfb_bin/PreMakeupBinary.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/pfb_bin/PreMakeupBinary.bin \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/pfb_bin/PreMakeupMultiFaceBinary.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/pfb_bin/PreMakeupMultiFaceBinary.bin \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/pfb_bin/PreMakeupMultiFaceBinaryV2.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/pfb_bin/PreMakeupMultiFaceBinaryV2.bin \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/pfb_bin/PreMakeupSingleFaceBinary.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/pfb_bin/PreMakeupSingleFaceBinary.bin \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/pfb_bin/PreMorphBinary.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/pfb_bin/PreMorphBinary.bin \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/pfb_bin/PreMorphBinaryV2.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/pfb_bin/PreMorphBinaryV2.bin \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/pfb_bin/PreOnlywhitenBinary.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/pfb_bin/PreOnlywhitenBinary.bin \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/pfb_bin/PreSkintuneBinary.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/pfb_bin/PreSkintuneBinary.bin \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/pfb_bin/PreSkintuneMRTBinary.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/pfb_bin/PreSkintuneMRTBinary.bin \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/pfb_bin/PreSurfaceBlurBinary.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/pfb_bin/PreSurfaceBlurBinary.bin \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/pfb_bin/PreVertFilterBinary.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/pfb_bin/PreVertFilterBinary.bin \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/pfb_bin/PreVertSurBinary.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/pfb_bin/PreVertSurBinary.bin \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/pfb_bin/ThirdPartyPreHoriFilterBinary.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/pfb_bin/ThirdPartyPreHoriFilterBinary.bin \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/pfb_bin/ThirdPartyPreMorphBinary.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/pfb_bin/ThirdPartyPreMorphBinary.bin \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/pfb_bin/ThirdPartyPreOnlywhitenBinary.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/pfb_bin/ThirdPartyPreOnlywhitenBinary.bin \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/pfb_bin/ThirdPartyPreSkintuneBinary.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/pfb_bin/ThirdPartyPreSkintuneBinary.bin \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/pfb_bin/ThirdPartyPreSkintuneMRTBinary.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/pfb_bin/ThirdPartyPreSkintuneMRTBinary.bin \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/pfb_bin/ThirdPartyPreVertFilterBinary.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/pfb_bin/ThirdPartyPreVertFilterBinary.bin \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/camera/pfb_bin/ThirdPartyPreVertSurBinary.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/pfb_bin/ThirdPartyPreVertSurBinary.bin \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/init/vendor.oplus.hardware.cryptoeng@1.0-service_FDE.rc:$(TARGET_COPY_OUT_ODM)/etc/init/vendor.oplus.hardware.cryptoeng@1.0-service_FDE.rc \
    vendor/oneplus/infiniti-camera/proprietary/odm/etc/permissions/vendor-oplus-hardware-cryptoeng.xml:$(TARGET_COPY_OUT_ODM)/etc/permissions/vendor-oplus-hardware-cryptoeng.xml \
    vendor/oneplus/infiniti-camera/proprietary/odm/firmware/secure_ta/cryptoeng.b00:$(TARGET_COPY_OUT_ODM)/firmware/secure_ta/cryptoeng.b00 \
    vendor/oneplus/infiniti-camera/proprietary/odm/firmware/secure_ta/cryptoeng.b01:$(TARGET_COPY_OUT_ODM)/firmware/secure_ta/cryptoeng.b01 \
    vendor/oneplus/infiniti-camera/proprietary/odm/firmware/secure_ta/cryptoeng.b02:$(TARGET_COPY_OUT_ODM)/firmware/secure_ta/cryptoeng.b02 \
    vendor/oneplus/infiniti-camera/proprietary/odm/firmware/secure_ta/cryptoeng.b03:$(TARGET_COPY_OUT_ODM)/firmware/secure_ta/cryptoeng.b03 \
    vendor/oneplus/infiniti-camera/proprietary/odm/firmware/secure_ta/cryptoeng.b04:$(TARGET_COPY_OUT_ODM)/firmware/secure_ta/cryptoeng.b04 \
    vendor/oneplus/infiniti-camera/proprietary/odm/firmware/secure_ta/cryptoeng.b05:$(TARGET_COPY_OUT_ODM)/firmware/secure_ta/cryptoeng.b05 \
    vendor/oneplus/infiniti-camera/proprietary/odm/firmware/secure_ta/cryptoeng.b06:$(TARGET_COPY_OUT_ODM)/firmware/secure_ta/cryptoeng.b06 \
    vendor/oneplus/infiniti-camera/proprietary/odm/firmware/secure_ta/cryptoeng.b07:$(TARGET_COPY_OUT_ODM)/firmware/secure_ta/cryptoeng.b07 \
    vendor/oneplus/infiniti-camera/proprietary/odm/firmware/secure_ta/cryptoeng.b08:$(TARGET_COPY_OUT_ODM)/firmware/secure_ta/cryptoeng.b08 \
    vendor/oneplus/infiniti-camera/proprietary/odm/firmware/secure_ta/cryptoeng.mdt:$(TARGET_COPY_OUT_ODM)/firmware/secure_ta/cryptoeng.mdt \
    vendor/oneplus/infiniti-camera/proprietary/system_ext/etc/camera/cdr_aging_set.json:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/camera/cdr_aging_set.json \
    vendor/oneplus/infiniti-camera/proprietary/system_ext/etc/camera/engineer_camera_config.json:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/camera/engineer_camera_config.json \
    vendor/oneplus/infiniti-camera/proprietary/system_ext/etc/camera/mt105CalibrationCfg.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/camera/mt105CalibrationCfg.xml \
    vendor/oneplus/infiniti-camera/proprietary/system_ext/etc/camera/mtCalibrationCfg.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/camera/mtCalibrationCfg.xml \
    vendor/oneplus/infiniti-camera/proprietary/system_ext/etc/camera/mwCalibrationCfg.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/camera/mwCalibrationCfg.xml \
    vendor/oneplus/infiniti-camera/proprietary/system_ext/etc/default-permissions/oplus_camera_default_grant_permissions_list.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/default-permissions/oplus_camera_default_grant_permissions_list.xml \
    vendor/oneplus/infiniti-camera/proprietary/system_ext/etc/permissions/vendor-oplus-hardware-cryptoeng.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/vendor-oplus-hardware-cryptoeng.xml \
    vendor/oneplus/infiniti-camera/proprietary/vendor/lib64/qsn1nrt430.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/qsn1nrt430.bin \
    vendor/oneplus/infiniti-camera/proprietary/vendor/lib64/qsn1nrt43270.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/qsn1nrt43270.bin \
    vendor/oneplus/infiniti-camera/proprietary/vendor/lib64/qsn1rt1690_vga.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/qsn1rt1690_vga.bin \
    vendor/oneplus/infiniti-camera/proprietary/vendor/lib64/qsn1rt169270_vga.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/qsn1rt169270_vga.bin \
    vendor/oneplus/infiniti-camera/proprietary/vendor/lib64/qsn1rt430_vga.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/qsn1rt430_vga.bin \
    vendor/oneplus/infiniti-camera/proprietary/vendor/lib64/qsn1rt43270_vga.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/qsn1rt43270_vga.bin \
    vendor/oneplus/infiniti-camera/proprietary/vendor/lib64/qsn2all.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/qsn2all.bin \
    vendor/oneplus/infiniti-camera/proprietary/vendor/lib64/qsn3_video.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/qsn3_video.bin \
    vendor/oneplus/infiniti-camera/proprietary/vendor/lib64/qsn3all.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/qsn3all.bin

PRODUCT_PACKAGES += \
    vendor.oplus.hardware.cameraextension-V1-ndk \
    vendor.oplus.hardware.cameraextension@1.0 \
    vendor.oplus.hardware.sendextcamcmd-V2-ndk_system \
    libpenguin \
    libNoTopK_aonservice \
    libPOSTPROCESS_aonservice \
    libROTATE90PAD_aonservice \
    libaiboost_jni_aonservice \
    libaiunit_framework_aiunit_aiunit \
    libaiunit_framework_jni_aiunit_aiunit \
    libaiunit_sdk_core_aimemory_aimemory \
    libaiunit_sdk_core_aiunit_aiunit \
    libbitmapUtil_aonservice \
    libc++_aiunit_aiunit \
    libc++_shared_aiunit_aiunit \
    libcore_tokenizers_aiunit_aiunit \
    libdatastore_shared_counter_aiunit_aiunit \
    libdmabufheap_aiunit_aiunit \
    libfde_aonservice \
    libmemoryhelper_aonservice \
    libnoise_aimemory_aimemory \
    libopencv_java4_aiunit_aiunit \
    libopluslog_aimemory_aimemory \
    libscan_engine_decode_aimemory_aimemory \
    libscan_engine_detect_aimemory_aimemory \
    libtensorflowlite_aimemory_aimemory \
    libwb_tables_549543368749780587_1_aimemory \
    libwbkit-seckit3_aimemory \
    libAPSClient-alog-jni \
    libAPSClient-cmd-jni-extension.oplus \
    libAPSClient-cmd-jni \
    libAPSClient-jni \
    libAncFilter_jni \
    libAncHumBokeh-jni \
    libAncHumanDoubleExposure-jni \
    libAncHumanRetain-jni_v2 \
    libAncHumanSegFigureFusion-jni \
    libAncHumanVideo-jni \
    libApsFaceBeautyPreviewProductJni \
    libApsSuperEISPreviewJni \
    libAvatarEngineRender \
    libAvatarEngineRenderNative \
    libCombineLut \
    libCombineLutJni \
    libFileExtender-jni \
    libHdrTransform-platform-jni \
    libHeifEncoderWrapper \
    libHeifWinBufExchg-jni \
    libMsEffectSdk \
    libNativeWinBuffExchange \
    libOplusBlurPreviewJNI \
    libOplusStringJNI-extension.oplus \
    libOplusStringJNI \
    libSuperTextWrapper_system_ext \
    libXDocProcessSDK-jni \
    libXDocProcessSDK_system_ext \
    libYTCommon_system_ext \
    libapssuspend-jni.oplus \
    libarcsoft_panorama_burstcapture \
    libarcsoft_wideselfie \
    libbinauralrenderer_wrapper.qti \
    libbsproxy \
    libcsextimpl \
    libdcc_cipher_mcs_mcs \
    libdolbyeffect_4.1 \
    libextendfile_system_ext \
    libheytap_mcs_cipheralgo_fixed_mcs \
    libhoaeffects.qti \
    libhoaeffects_csim \
    libjni_burstpmk \
    libjni_wideselfie \
    libjnisingleblur_api \
    libjnistblur_api \
    liblivephoto.frc.jni \
    libmmkv_mcs_mcs \
    libmpbase_system_ext \
    liboplus-uah-client_system_ext \
    liboplus_conscrypt_jni_mcs \
    liboplusdolbyeffect_4.1 \
    liboplusgui_jni \
    liboplusheifwriter \
    libortc_so.oplus \
    libsatellite_audio_jni.oplus \
    libsingle_camera_bokeh2_native \
    libsingle_camera_bokeh_native \
    libsoundtouch.oplus \
    libsoundtouch_jni.oplus \
    libst_mobile \
    libst_sticker_jni \
    libsuperNight.oplus \
    libvr_amb_engine \
    vendor.oplus.hardware.cameraMDM@1.0 \
    vendor.oplus.hardware.cryptoeng-V1-ndk \
    vendor.oplus.hardware.cryptoeng@1.0 \
    lib_cryptoeng_api \
    libalogencrypt \
    libqsee_keybox_ca \
    vendor.oplus.hardware.cryptoeng-V1-ndk_odm \
    vendor.oplus.hardware.cryptoeng@1.0_odm \
    vendor.oplus.hardware.fido.fido2ca-V1-ndk \
    vendor.oplus.hardware.fido.fidoca-V1-ndk \
    camera.oemlayer.v2 \
    libOplusSecurity \
    libarcsoft_hdr_couple_api_V2 \
    libstblur_api \
    AONService \
    RomUpdate \
    AIMemory \
    AIUnit \
    FileManager \
    MCS \
    OpenCapabilityService \
    SafeCenter \
    SecurityPermission \
    StdSP \
    SystemUIPlugin \
    ambientalert \
    DCS \
    FileEncryption \
    OplusAppPlatform \
    OplusCamera \
    OplusExSystemService \
    oplus-services \
    OppoGallery2 \
    PhoneManager \
    StdID \
    UMS \
    com.oplus.camera.unit.sdk.adapter \
    com.oplus.camera.unit.sdk \
    vendor.oplus.hardware.cryptoeng-V1-java \
    vendor.oplus.hardware.cryptoeng-V1.0-java \
    manifest_oplus_cryptoeng.xml \
    vendor.oplus.hardware.cryptoeng@1.0-service

PRODUCT_PACKAGES += \
    product_app_AONService_lib_arm64_libNoTopK_so \
    product_app_AONService_lib_arm64_libPOSTPROCESS_so \
    product_app_AONService_lib_arm64_libROTATE90PAD_so \
    product_app_AONService_lib_arm64_libaiboost_jni_so \
    product_priv-app_AIUnit_lib_arm64_libaiunit_framework_so \
    product_priv-app_AIUnit_lib_arm64_libaiunit_framework_jni_so \
    product_priv-app_AIMemory_lib_arm64_libaiunit_sdk_core_so \
    product_priv-app_AIUnit_lib_arm64_libaiunit_sdk_core_so \
    product_app_AONService_lib_arm64_libbitmapUtil_so \
    product_priv-app_AIUnit_lib_arm64_libc++_so \
    product_priv-app_AIUnit_lib_arm64_libc++_shared_so \
    product_priv-app_AIUnit_lib_arm64_libcore_tokenizers_so \
    product_priv-app_AIUnit_lib_arm64_libdatastore_shared_counter_so \
    product_priv-app_AIUnit_lib_arm64_libdmabufheap_so \
    product_app_AONService_lib_arm64_libfde_so \
    product_app_AONService_lib_arm64_libmemoryhelper_so \
    product_priv-app_AIMemory_lib_arm64_libnoise_so \
    product_priv-app_AIUnit_lib_arm64_libopencv_java4_so \
    product_priv-app_AIMemory_lib_arm64_libopluslog_so \
    product_priv-app_AIMemory_lib_arm64_libscan_engine_decode_so \
    product_priv-app_AIMemory_lib_arm64_libscan_engine_detect_so \
    product_priv-app_AIMemory_lib_arm64_libtensorflowlite_so \
    product_priv-app_AIMemory_lib_arm64_libwb_tables_549543368749780587_1_so \
    product_priv-app_AIMemory_lib_arm64_libwbkit-seckit3_so \
    system_ext_app_MCS_lib_arm64_libdcc_cipher_so \
    system_ext_app_MCS_lib_arm64_libheytap_mcs_cipheralgo_fixed_so \
    system_ext_app_MCS_lib_arm64_libmmkv_so \
    system_ext_app_MCS_lib_arm64_liboplus_conscrypt_jni_so
